strings = {
    "UnsuccessfulMessage": "ظاهرا خطایی در سرویسهای تامین کننده رخ داده است، جهت رفع مشکل با مراکز پشتیبانی بلو تماس "
                           "بگیرید.",
    "err_invalid_username_or_password": "دوست عزیز، نام کاربری یا رمز عبور اشتباه می باشد.",
    "err_empty_username": "نام کاربری لازم است.",
    "err_empty_password": "رمز عبور لازم است.",
    "CameraScanBackIdCardPageSubTitle": "پشت کارت ملی خود را مقابل دوربین قرار دهید یا از گالری انتخاب کنید",
    "ConfirmScanBottomSheetTitle": "بررسی مدارک",
    "ConfirmScanBottomSheetSubTitle": "قبل از ارسال مدارک به موارد زیر توجه کنید",
    "ConfirmScanBottomSheetAlert": "تصویر روی کارت ملی نادرست است",
    "ConfirmScanBottomSheetSendImage": "ارسال تصاویر",
    "ConfirmScanBottomSheetRetry": "اسکن دوباره کارت ملی",
    "ConfirmButtonConfirmScan": "تایید",
    "ConfirmButtonConfirmScanKYC": "تایید و ارسال",
    "RetryScanButton": "اسکن دوباره کارت ملی",
    "ConfirmScanPageSubTitle": "تصویر و اطلاعات کارت ملی خود را تایید کنید",
    "CameraScanIdCardPageSubTitle": "روی کارت ملی خود را مقابل دوربین قرار دهید یا از گالری انتخاب کنید",
    "selectDocPageSubTitle": "یکی از گزینه‌های زیر را انتخاب کنید",
    "IDCardButtonDocPage": "کارت ملی هوشمند دارم",
    "TrackerIDButtonDocPage": "شناسنامه و کد رهگیری دارم",
    "TrackerPageSubTitle": "کد رهگیری نوشته شده بر روی رسید ثبت‌نام کارت ملی هوشمند خود را وارد کنید",
    "PasswordPageField": "مانند: ۱۲۳۴۵۶۷۸۹",
    "PasswordPageSubTitle": "رمز عبور امنی برای خود انتخاب کنید",
    "PasswordPageDescription1": "شامل حروف کوچک و بزرگ انگلیسی",
    "PasswordPageDescription2": "شامل حداقل ۸ کاراکتر",
    "PasswordPageDescription3": "شامل عدد",
    "PasswordPageHint": "رمز عبور شما همان رمز بانکی شماست!",
    "PasswordPageFld": "رمز عبور",
    "startDateTransfer": "تاریخ شروع",
    "usernamePageHint": "نام کاربری دلخواه خود را وارد کنید",
    "usernameField": "مانند: blu",
    "endDateTransfer": "تاریخ پایان",
    "countTransferTitle": "تعداد انتقال",
    "periodTransfer": "دوره انتقال",
    "MethodTransfer": "روش انتقال",
    "RangeInputTitle": "تعداد روزهای تکرار",
    "OnceDetail": "یکبار",
    "EmptyStateScheduleTitle": "انتقال در آینده ندارید",
    "TransactionsTitle": "انتقال‌ها",
    "TransferMethod": "روش انتقال",
    "PeriodTransfer": "دوره انتقال",
    "AMOUNT": "مبلغ",
    "DetailContractTitle": "جزئیات انتقال",
    "headerScheduleTransferContracts": "انتقال‌های خودکار",
    "FirstDateTransfer": "تاریخ اولین انتقال",
    "TransferDate": "تاریخ انتقال",
    "FirstTransferDate": "تاریخ اولین انتقال",
    "Monthly": "ماهانه",
    "Weekly": "هفتگی",
    "Daily": "روزانه",
    "Once": "یک‌بار",

}

